security:
    firewalls:
        # Firewall for login, no security applied to /login
        login:
            pattern: ^/login$
            security: false

            

        # Secured area for customer, ensure there's no protection on /customer
        secured_area:
            pattern: ^/customer
            security: false  # Disable security for the customer area

    # Define the access control outside of the firewalls section
    access_control:
        - { path: ^/customer, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Allow anonymous access to /customer
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Allow anonymous access to /login
